import "../styles/globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Providers from "@/utils/Providers";
import { Container, Grid } from "@mui/material";
import { Header } from "@/components/Header";

const inter = Lato({ weight: ["400", "700", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Users posts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Container maxWidth="md">
            <Header />
            <main>
              <Grid container justifyContent="center">
                {children}
              </Grid>
            </main>
          </Container>
        </Providers>
      </body>
    </html>
  );
}
